import type { Metadata } from "next";
import { Suspense } from "react";
import { Header } from "widgets/header";

export const metadata: Metadata = {
  title: "Tasty Shop | Главная",
  description: "Generated by create next app",
};

export default function HomeLayout({
  children,
  modal,
}: Readonly<{
  children: React.ReactNode;
  modal: React.ReactNode;
}>) {
  return (
    <div className="min-h-screen bg-white">
      <Header />
      <main>
        <Suspense>{children}</Suspense>
        <Suspense>{modal}</Suspense>
      </main>
    </div>
  );
}
