import type { Metadata } from "next";
import { Suspense } from "react";
import { Header } from "shared/components/shared/Header";

export const metadata: Metadata = {
  title: "Tasty Shop | Главная",
  description: "Generated by create next app",
};

export default function HomeLayout({
  children,
  modal,
}: Readonly<{
  children: React.ReactNode;
  modal: React.ReactNode;
}>) {
  return (
    <main className="min-h-screen bg-white">
      <Header />
      <Suspense>{children}</Suspense>
      <Suspense>{modal}</Suspense>
    </main>
  );
}
