import type { Metadata } from "next";
import { Header } from "shared/components/shared";

export const metadata: Metadata = {
  title: "Tasty Shop | Корзина",
  description: "Generated by create next app",
};

export default async function CheckoutLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <main className="min-h-screen bg-page-bg">
      <Header className="border-gray-200" hasSearch={false} hasCart={false} />
      {children}
    </main>
  );
}
